import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import type { ReactNode } from "react";
import DisplayedModal from "./components/Feedback/DisplayedModal";
import CartContext from "./context/CartContext";
import ModalContext from "./context/ModalContext";
import { TableContext } from "./context/TableContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Route = {
  value: string;
  name: string;
};

const ROUTS: Route[] = [
  { name: "Home", value: "/" },
  { name: "Storage", value: "/storage" },
  { name: "Overview", value: "/overview" },
  { name: "Products", value: "/products" },
  { name: "Parts", value: "/parts" },
  { name: "Orders", value: "/orders" },
  { name: "Operations", value: "/operations" },
];

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: ReactNode;
  modal: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TableContext>
          <ModalContext>
            <CartContext>
              <nav className="bg-gradient-to-r from-green-600 to-blue-500 p-4 flex gap-8 text-white h-[49px]">
                {ROUTS.map((route) => (
                  <Link key={route.value} href={route.value}>
                    {route.name}
                  </Link>
                ))}
              </nav>
              {modal}
              {children}
              <DisplayedModal />
            </CartContext>
          </ModalContext>
        </TableContext>
      </body>
    </html>
  );
}
