import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ModalContext from "./_context/ModalContext";
import { TableContext } from "./_context/TableContext";
import { DeliveryContext } from "./_context/DeliveryContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="overflow-hidden" lang="en">
      <body className={inter.className}>
        <TableContext>
          <DeliveryContext>
            <ModalContext>{children}</ModalContext>
          </DeliveryContext>
        </TableContext>
      </body>
    </html>
  );
}
