name: GitHub Actions Vercel Production Deployment
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./github/actions/deploy-vercel
        with:
         vercel-token: ${{ secrets.VERCEL_TOKEN }}
         mode: production
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}